CREATE TABLE IF NOT EXISTS shops (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    rating INT NOT NULL,
    budget VARCHAR(50) NOT NULL,
    hideaway_level VARCHAR(50),
    comment VARCHAR(500) NOT NULL,
    reaction_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
